### ISSUE TITLE
Ignore phantom type variables

### ISSUE THREAD

**Issue by jberdine** [janestreet/ppx_compare#3]
For types with polymorphic type variables that do not appear in the definition, ppx_compare generates comparison functions that still require a comparison function argument for the phantom type.  It would be nice if ppx_compare noticed if a type parameter is phantom and if so did not require a comparison function for it.

**Comment by bmillwood** [comment]
The trouble with this is:

    type t = Percent.t Thing.t [@@deriving compare]
    (* generates: *)
    let compare = Thing.compare Percent.compare

We can't tell in this context whether `Thing.t` is a phantom type, because we don't have access to its declaration. So we can't tell if `Thing.compare` will need `Percent.compare` or not. So we have no choice but to pass it.

In principle you could have the `[@@deriving compare]` on `Thing.t` generate some kind of specification data, `How_to_compare_me.t` or something. But I doubt it's worth the additional complexity.

**Comment by jberdine** [comment]
Very good point, and I agree about the complexity of generating extra spec data.  Maybe if one day there is something analogous to ppx that operates on the typed trees...
